# MySQL. Versions 5.7
default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: kapiTech-api_development

test:
  <<: *default
  database: kapiTech-api_test

production:
  <<: *default
  database: kapiTech-api_production
