# MySQL. Versions 5.6
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: kapiTech-api_development
  username: root
  password: root

test:
  <<: *default
  database: kapiTech-api_test
  username: root
  password: root

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] %>
  socket: /var/lib/mysql/mysql.sock
  #username: <%= ENV['RDS_USERNAME'] %>
  #password: <%= ENV['RDS_PASSWORD'] %>
  #host: <%= ENV['RDS_HOSTNAME'] %>
  #port: <%= ENV['RDS_PORT'] %>
