# MySQL. Versions 5.6
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: kapiTech-api_development
  username: root
  password:

test:
  <<: *default
  database: kapiTech-api_test
  username: root
  password:

production:
  <<: *default
  database: kapiTech_api_production
  username: admin
  password: buena926
  socket: /var/lib/mysql/mysql.sock
  host: kapi-tech-mysql.cmrxvnzyzbv4.ap-northeast-1.rds.amazonaws.com
  port: 3306
  #username: <%= ENV['RDS_USERNAME'] %>
  #password: <%= ENV['RDS_PASSWORD'] %>
  #host: <%= ENV['RDS_HOSTNAME'] %>
  #port: <%= ENV['RDS_PORT'] %>
